/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIExample */

#ifndef _Included_JNIExample
#define _Included_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     JNIExample
	 * Method:    sum
	 * Signature: (II)I
	 */
	JNIEXPORT jint JNICALL Java_JNIExample_sum
	(JNIEnv*, jobject, jint, jint);

	/*
	 * Class:     JNIExample
	 * Method:    quickSort
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_JNIExample_quickSort
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
